import Sidebar from '~/components/sidebar';

import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // className={cn(
  //   inter.className,
  //   'bg-slate-50 dark:bg-slate-900 text-slate-800 dark:text-slate-200',
  // )}
  return (
    <html lang="en">
      <body
        className={
          (inter.className,
          'flex-1 md:grid md:grid-cols-[70px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[220px_minmax(0,1fr)] lg:gap-8')
        }
      >
        <aside className="border-r">
          <Sidebar />
        </aside>
        <main className="border border-red-200">{children}</main>
      </body>
    </html>
  );
}
