import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // className={cn(
  //   inter.className,
  //   'bg-slate-50 dark:bg-slate-900 text-slate-800 dark:text-slate-200',
  // )}
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
