import { DashboardHeader } from '~/components/header';
import { DashboardShell } from '~/components/shell';

export default function Cards() {
  return (
    <DashboardShell>
      <DashboardHeader
        heading="Cards"
        text="This is where you will find all the cards generated by your customers"
      />
    </DashboardShell>
  );
}
