name: Bug report
description: Create a report to help us address an error.
title: '[BUG] - <bug description>'
labels: ['🚦 status: awaiting triage']
body:
  - type: markdown
    attributes:
      value: '# Bug report'
  - type: textarea
    id: bug_description
    attributes:
      label: What bug did you encounter?
      description: |
        Please provide a clear description of the bug.

        Include the steps you took to cause the bug, and an explanation of what occurred.
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: What did you expect to happen?
      description: What did you expect to happen instead of the current behavior?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Attach any relevant screenshots here.
    validations:
      required: false
  - type: textarea
    id: extra_information
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/TAKANOME-DEV/click-to-buy/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
